import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Partnerwithus: NextPage = () => {
    return (
      <div className={styles.container}>
        <Head>
          <title>Partner with us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Partner with us</h1>
        <footer className={styles.footer}>
 
        </footer>
      </div>
    )
  }
  
  export default Partnerwithus
  